---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /srv/dev-disk-by-label-NAS/Config/Plex:/config
      - /srv/dev-disk-by-label-NAS/Data/Series:/tv
      - /srv/dev-disk-by-label-NAS/Data/Movies:/movies
      - /srv/dev-disk-by-label-NAS/Data/Music:/music
    restart: unless-stopped        